### ISSUE TITLE
お題: 成人式

### ISSUE THREAD

**Issue by ryosms** [kakenavi/OGIRI#1]

**Comment by tamacjp** [comment]
成人式とかけまして
フィーバーと解きます

**Comment by tamacjp** [comment]
あれ、これ謎かけやん

**Comment by tamacjp** [comment]
ひぬぜもしおごほぷとぱれりはへぱべあらのしあずずやはまえりぎばへあねざげゆかろかぱがわみべくてそさぞちきめぬぷふる

**Comment by eiel** [comment]
成人式いったはずなのに内容をまったく知らない。

**Comment by kakenavi** [comment]
成人式でテレビの取材を受け「ハタチになったらなにをしたいですか？」との質問に「禁煙」と答えたら放送されなかった。

**Comment by Torokun** [comment]
禁酒はハタチから

**Comment by ryosms** [comment]
時期過ぎたので
